"""add_content_hash_and_rename_parent_to_previous_hash

Revision ID: 7a3a43cd6667
Revises: 4a63d38668cd
Create Date: 2026-03-24 22:43:53.516662+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a3a43cd6667"
down_revision = "4a63d38668cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column("outputs", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.add_column("outputs", sa.Column("previous_hash", sa.String(length=64), nullable=True))

    # Migrate existing data: copy hash to content_hash and parent_hash to previous_hash
    op.execute("UPDATE outputs SET content_hash = hash WHERE content_hash IS NULL")
    op.execute("UPDATE outputs SET previous_hash = parent_hash WHERE previous_hash IS NULL")

    # Now make content_hash non-nullable
    op.alter_column("outputs", "content_hash", nullable=False)

    # Create indexes and constraints
    op.create_index(op.f("ix_outputs_content_hash"), "outputs", ["content_hash"], unique=False)
    op.create_index(op.f("ix_outputs_previous_hash"), "outputs", ["previous_hash"], unique=False)
    op.create_unique_constraint(None, "outputs", ["hash"])

    # Drop old parent_hash column
    op.drop_column("outputs", "parent_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outputs",
        sa.Column("parent_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "outputs", type_="unique")
    op.drop_index(op.f("ix_outputs_previous_hash"), table_name="outputs")
    op.drop_index(op.f("ix_outputs_content_hash"), table_name="outputs")
    op.drop_column("outputs", "previous_hash")
    op.drop_column("outputs", "content_hash")
    # ### end Alembic commands ###
