"""Add output_follows table with correct types

Revision ID: 78ab6f56a770
Revises: 39bf3554a384
Create Date: 2026-03-24 13:24:31.695323+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78ab6f56a770"
down_revision = "39bf3554a384"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "output_follows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("output_id", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["output_id"], ["outputs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "output_id", name="uq_user_output"),
    )
    op.create_index(
        op.f("ix_output_follows_output_id"), "output_follows", ["output_id"], unique=False
    )
    op.create_index(op.f("ix_output_follows_user_id"), "output_follows", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_output_follows_user_id"), table_name="output_follows")
    op.drop_index(op.f("ix_output_follows_output_id"), table_name="output_follows")
    op.drop_table("output_follows")
    # ### end Alembic commands ###
