"""rename_parent_hash_to_previous_hash_in_output_history

Revision ID: 6bd7993a6a6a
Revises: 7a3a43cd6667
Create Date: 2026-03-24 22:49:21.167796+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bd7993a6a6a"
down_revision = "7a3a43cd6667"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column
    op.add_column("output_history", sa.Column("previous_hash", sa.String(length=64), nullable=True))

    # Migrate existing data
    op.execute("UPDATE output_history SET previous_hash = parent_hash WHERE previous_hash IS NULL")

    # Drop old column
    op.drop_column("output_history", "parent_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "output_history",
        sa.Column("parent_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.drop_column("output_history", "previous_hash")
    # ### end Alembic commands ###
