"""add_protocol_agreement_to_users

Revision ID: 9c1cab355ad6
Revises: 6bd7993a6a6a
Create Date: 2026-03-25 00:58:19.401659+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c1cab355ad6"
down_revision = "6bd7993a6a6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column("users", sa.Column("has_agreed_to_protocol", sa.Boolean(), nullable=True))

    # Set default value for existing users (False - they need to agree)
    op.execute("UPDATE users SET has_agreed_to_protocol = FALSE WHERE has_agreed_to_protocol IS NULL")

    # Make it non-nullable
    op.alter_column("users", "has_agreed_to_protocol", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_agreed_to_protocol")
    # ### end Alembic commands ###
