"""Initial schema

Revision ID: bfa3aeac3bd3
Revises: 
Create Date: 2026-03-24 02:29:32.748597+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bfa3aeac3bd3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("age_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "follows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followed_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["followed_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "followed_id", name="uq_follower_followed"),
    )
    op.create_index(op.f("ix_follows_followed_id"), "follows", ["followed_id"], unique=False)
    op.create_index(op.f("ix_follows_follower_id"), "follows", ["follower_id"], unique=False)
    op.create_table(
        "outputs",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SCIENCE",
                "ART",
                "PHILOSOPHY",
                "TECHNOLOGY",
                "SOCIETY",
                "OTHER",
                name="category_enum",
            ),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column(
            "visibility", sa.Enum("PUBLIC", "PRIVATE", name="visibility_enum"), nullable=False
        ),
        sa.Column(
            "ai_review_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="ai_review_status_enum"),
            nullable=False,
        ),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("parent_hash", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outputs_created_at"), "outputs", ["created_at"], unique=False)
    op.create_index(op.f("ix_outputs_novelty_score"), "outputs", ["novelty_score"], unique=False)
    op.create_index(op.f("ix_outputs_user_id"), "outputs", ["user_id"], unique=False)
    op.create_index(op.f("ix_outputs_visibility"), "outputs", ["visibility"], unique=False)
    op.create_table(
        "agreements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("output_id", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["output_id"], ["outputs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "output_id", name="uq_user_output_agreement"),
    )
    op.create_index(op.f("ix_agreements_created_at"), "agreements", ["created_at"], unique=False)
    op.create_index(op.f("ix_agreements_output_id"), "agreements", ["output_id"], unique=False)
    op.create_table(
        "citations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_output_id", sa.String(length=30), nullable=False),
        sa.Column("target_output_id", sa.String(length=30), nullable=False),
        sa.Column(
            "citation_type",
            sa.Enum("AGREE", "CRITICIZE", "DEVELOP", "REFERENCE", name="citation_type_enum"),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_output_id"], ["outputs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_output_id"], ["outputs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_output_id", "target_output_id", "citation_type", name="uq_citation"
        ),
    )
    op.create_index(
        op.f("ix_citations_source_output_id"), "citations", ["source_output_id"], unique=False
    )
    op.create_index(
        op.f("ix_citations_target_output_id"), "citations", ["target_output_id"], unique=False
    )
    op.create_table(
        "output_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("output_id", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("parent_hash", sa.String(length=64), nullable=True),
        sa.Column("edited_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["edited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["output_id"], ["outputs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_output_history_output_id"), "output_history", ["output_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_output_history_output_id"), table_name="output_history")
    op.drop_table("output_history")
    op.drop_index(op.f("ix_citations_target_output_id"), table_name="citations")
    op.drop_index(op.f("ix_citations_source_output_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index(op.f("ix_agreements_output_id"), table_name="agreements")
    op.drop_index(op.f("ix_agreements_created_at"), table_name="agreements")
    op.drop_table("agreements")
    op.drop_index(op.f("ix_outputs_visibility"), table_name="outputs")
    op.drop_index(op.f("ix_outputs_user_id"), table_name="outputs")
    op.drop_index(op.f("ix_outputs_novelty_score"), table_name="outputs")
    op.drop_index(op.f("ix_outputs_created_at"), table_name="outputs")
    op.drop_table("outputs")
    op.drop_index(op.f("ix_follows_follower_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_followed_id"), table_name="follows")
    op.drop_table("follows")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
