"""Add OAuth fields to User model

Revision ID: 39bf3554a384
Revises: bfa3aeac3bd3
Create Date: 2026-03-24 11:58:08.927760+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39bf3554a384"
down_revision = "bfa3aeac3bd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("oauth_provider", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("oauth_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "oauth_id")
    op.drop_column("users", "oauth_provider")
    # ### end Alembic commands ###
