"""Add script, place, experience categories to CategoryEnum

Revision ID: 4a63d38668cd
Revises: 78ab6f56a770
Create Date: 2026-03-24 21:52:13.937812+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a63d38668cd"
down_revision = "78ab6f56a770"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
